name: barcode_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_gallery_saver: ^1.1.0
  image_picker: ^0.6.1+4
  password_hash: 2.0.0
  imei_plugin: 1.2.0
  percent_indicator: ^2.1.9+1
  flutter_barcode_scanner: ^2.0.0
  splashscreen: ^1.2.0
  vibration: ^1.7.3
  flutter_launcher_icons: ^0.8.1
  audioplayers: 0.14.0
  progress_dialog: ^1.2.4
  flutter_phoenix: ^1.0.0
  encrypt: ^4.1.0
  geolocator: 5.3.1
  awesome_dialog:
  dio: 3.0.10
  platform_device_id: 0.2.0
  shared_preferences: 0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
